server:
  port: 8090
spring:
  application:
    name: passenger-api
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
dubbo:
  application:
    name: passenger-dubbo-demo
  scan:
    base-packages: com.alibaba.cloud.youxia
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: localhost:8848